#ifndef GAMUT_H
#define GAMUT_H

/* Generated by cbindgen from gamut-ffi — do not edit; run `mise run gen-ffi-header`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * The number of plane slots in a `GamutImageDesc` (the C spelling of
 * [`gamut_codec_abi::MAX_PLANES`]).
 *
 * A literal so cbindgen can emit the `#define` that sizes the header's plane arrays; the
 * const assert below locks it to the seam's value.
 */
#define GAMUT_MAX_PLANES 4

/**
 * The `gamut-codec-abi` seam revision this library was built against. A pushed vtable's
 * `abi_version` field must equal this value or `push_backend` returns
 * [`GAMUT_STATUS_ABI_MISMATCH`].
 *
 * A literal (not `gamut_codec_abi::ABI_VERSION`) so cbindgen can emit it; the const assert
 * below locks the two together, so a seam bump fails this build until the value — and the
 * header — are consciously updated.
 */
#define GAMUT_CODEC_ABI_VERSION 1

/**
 * Opaque handle over a `gamut::avif::AvifEncoder` and its backend registry.
 */
typedef struct GamutAvifEncoder GamutAvifEncoder;

/**
 * Opaque handle over the HEIC HEVC-decode backend registry (push order).
 */
typedef struct GamutHeicDecoder GamutHeicDecoder;

/**
 * Opaque handle over a `gamut::jpeg::JpegDecoder` and its backend registry.
 */
typedef struct GamutJpegDecoder GamutJpegDecoder;

/**
 * Opaque handle over a `gamut::jpeg::JpegEncoder` and its backend registry.
 */
typedef struct GamutJpegEncoder GamutJpegEncoder;

/**
 * Opaque handle over a `gamut::jxl::JxlDecoder` and its backend registry.
 */
typedef struct GamutJxlDecoder GamutJxlDecoder;

/**
 * Opaque handle over a `gamut::jxl::JxlEncoder` and its backend registry.
 */
typedef struct GamutJxlEncoder GamutJxlEncoder;

/**
 * Opaque handle over a `gamut::png::PngDecoder` and its backend registry.
 */
typedef struct GamutPngDecoder GamutPngDecoder;

/**
 * Opaque handle over a `gamut::png::PngEncoder` and its backend registry.
 */
typedef struct GamutPngEncoder GamutPngEncoder;

/**
 * Opaque handle over a `gamut::webp::WebpDecoder` and its backend registry.
 */
typedef struct GamutWebpDecoder GamutWebpDecoder;

/**
 * Opaque handle over a `gamut::webp::WebpEncoder` and its backend registry.
 */
typedef struct GamutWebpEncoder GamutWebpEncoder;

/**
 * A `gamut` entry-point result (`gamut_status_t` in the C header): [`GAMUT_OK`] is success,
 * every other value is one of the permanent `GAMUT_STATUS_*` codes below.
 */
typedef int32_t gamut_status_t;

/**
 * A backend result code, `repr(transparent)` over `i32` so it round-trips a C `int`.
 *
 * `0` ([`Status::OK`]) is success. `-1` ([`Status::UNSUPPORTED`]) is the *fall-through* code: it is
 * the only value that tells a host to try the next backend in its registry. Any other value is a
 * terminal backend-specific error that propagates to the caller unchanged.
 */
typedef int32_t GamutAbiStatus;
/**
 * Success (`0`).
 */
#define GamutAbiStatus_OK 0
/**
 * The backend cannot handle this job (`-1`); the host falls back to the next backend.
 */
#define GamutAbiStatus_UNSUPPORTED -1

/**
 * Describes an encode job to an encoder backend: the target codec, a quality knob, and an opaque
 * codec-specific options blob.
 *
 * Leads with [`struct_size`](Self::struct_size) for forward-compatible field growth.
 */
typedef struct GamutEncodeConfig {
  /**
   * `size_of::<EncodeConfig>()` as written by the producer; the ABI version guard for this
   * descriptor. See [`EncodeConfig::is_abi_current`].
   */
  size_t struct_size;
  /**
   * Host/backend-agreed codec identifier (e.g. a FourCC or an enum discriminant).
   */
  uint32_t codec_id;
  /**
   * Quality target on a `0..=100` scale (higher is better quality / larger output); a backend
   * clamps out-of-range values.
   */
  uint32_t quality;
  /**
   * Pointer to an opaque, codec-specific options blob, or null when there is none. Borrowed for
   * the duration of the call; the backend must not retain it.
   */
  const void *extra;
  /**
   * Length in bytes of [`extra`](Self::extra); `0` when there is none.
   */
  size_t extra_len;
} GamutEncodeConfig;

/**
 * A raw image buffer shared across the seam: the pixel layout, dimensions, and plane pointers.
 *
 * The same descriptor is used both ways. As an **encode input** the planes are read; as a **decode
 * output** (`out` in [`Decoder::decode`]) the decoder writes reconstructed samples through the
 * plane pointers. In both directions the buffer is caller-allocated and borrowed for the call.
 *
 * Leads with [`struct_size`](Self::struct_size) for forward-compatible field growth.
 */
typedef struct GamutImageDesc {
  /**
   * `size_of::<ImageDesc>()` as written by the producer; the ABI version guard for this
   * descriptor. See [`ImageDesc::is_abi_current`].
   */
  size_t struct_size;
  /**
   * Host/backend-agreed pixel-format tag (mirrors `gamut_core::PixelFormat`'s discriminants at
   * the wiring layer; kept a plain `u32` here to keep this crate dependency-free).
   */
  uint32_t pixel_format;
  /**
   * Image width in pixels.
   */
  uint32_t width;
  /**
   * Image height in pixels.
   */
  uint32_t height;
  /**
   * Bits per component (e.g. `8`, `16`).
   */
  uint32_t depth;
  /**
   * Number of populated entries in [`planes`](Self::planes) / [`strides`](Self::strides);
   * `1..=MAX_PLANES`.
   */
  uint32_t plane_count;
  /**
   * Per-plane row-start pointers; only the first [`plane_count`](Self::plane_count) are valid.
   * Unused entries are null.
   */
  uint8_t *planes[GAMUT_MAX_PLANES];
  /**
   * Per-plane row stride in bytes; only the first [`plane_count`](Self::plane_count) are valid.
   */
  size_t strides[GAMUT_MAX_PLANES];
} GamutImageDesc;

/**
 * A C callback that receives one chunk of encoder output.
 *
 * The encoder calls it zero or more times over the course of an encode; `ctx` is the opaque sink
 * pointer passed alongside it, `data`/`len` the bytes. Returning a non-[`Status::OK`] code asks the
 * encoder to abort (the encoder should propagate that status).
 *
 * # Safety
 *
 * The implementation must treat `data` as valid for `len` bytes only for the duration of the call,
 * and `ctx` as the exact pointer it was handed.
 */
typedef GamutAbiStatus (*GamutWriteFn)(void *ctx, const uint8_t *data, size_t len);

/**
 * The `repr(C)` encoder backend: an [`abi_version`](Self::abi_version) tag plus function pointers
 * over an opaque `ctx`. The C twin of [`Encoder`].
 *
 * Output is delivered through a [`WriteFn`] + sink `ctx` the host passes into `encode`, so the
 * encoder streams bytes without owning the output buffer. Function-pointer nullability follows the
 * same rules as [`DecoderVTable`].
 */
typedef struct GamutEncoderVTable {
  /**
   * Must equal [`ABI_VERSION`]; a host rejects any other value.
   */
  uint32_t abi_version;
  /**
   * Reports whether the backend can satisfy the given encode job. `ctx` is the backend context.
   */
  GamutAbiStatus (*supports)(void *ctx, const struct GamutEncodeConfig *cfg);
  /**
   * Encodes `image`, streaming output through `write`/`write_ctx`. `ctx` is the backend context.
   */
  GamutAbiStatus (*encode)(void *ctx,
                           const struct GamutEncodeConfig *cfg,
                           const struct GamutImageDesc *image,
                           GamutWriteFn write,
                           void *write_ctx);
  /**
   * Releases the backend context. Called exactly once, when the host drops the backend.
   */
  void (*destroy)(void *ctx);
} GamutEncoderVTable;

/**
 * Describes a coded stream to a decoder backend: the codec, the coded dimensions, and any
 * out-of-band configuration (parameter sets, `hvcC`/`av1C` records, …).
 *
 * Leads with [`struct_size`](Self::struct_size) for forward-compatible field growth: a reader
 * trusts only the fields covered by `struct_size`.
 */
typedef struct GamutStreamConfig {
  /**
   * `size_of::<StreamConfig>()` as written by the producer; the ABI version guard for this
   * descriptor. See [`StreamConfig::is_abi_current`].
   */
  size_t struct_size;
  /**
   * Host/backend-agreed codec identifier (e.g. a FourCC or an enum discriminant).
   */
  uint32_t codec_id;
  /**
   * Coded width in pixels.
   */
  uint32_t width;
  /**
   * Coded height in pixels.
   */
  uint32_t height;
  /**
   * Bits per component of the coded samples (e.g. `8`, `10`, `12`).
   */
  uint32_t bit_depth;
  /**
   * Pointer to codec extradata (parameter sets / config record), or null when there is none.
   * Borrowed for the duration of the call; the backend must not retain it.
   */
  const uint8_t *extradata;
  /**
   * Length in bytes of [`extradata`](Self::extradata); `0` when there is none.
   */
  size_t extradata_len;
} GamutStreamConfig;

/**
 * The `repr(C)` decoder backend: an [`abi_version`](Self::abi_version) tag plus function pointers
 * over an opaque `ctx`. The C twin of [`Decoder`].
 *
 * Each function pointer is [`Option`]-wrapped (a null C pointer): a `None` `supports` reads as
 * "supports nothing", a `None` `decode` as [`Status::UNSUPPORTED`], and a `None` `destroy` as
 * "no teardown". The first argument of every call is the backend's own `ctx`.
 */
typedef struct GamutDecoderVTable {
  /**
   * Must equal [`ABI_VERSION`]; a host rejects any other value.
   */
  uint32_t abi_version;
  /**
   * Reports whether the backend can decode the given stream. `ctx` is the backend context.
   */
  GamutAbiStatus (*supports)(void *ctx, const struct GamutStreamConfig *cfg);
  /**
   * Decodes `codestream` into the caller-allocated `out` planes. `ctx` is the backend context.
   */
  GamutAbiStatus (*decode)(void *ctx,
                           const struct GamutStreamConfig *cfg,
                           const uint8_t *codestream,
                           size_t codestream_len,
                           const struct GamutImageDesc *out);
  /**
   * Releases the backend context. Called exactly once, when the host drops the backend.
   */
  void (*destroy)(void *ctx);
} GamutDecoderVTable;

/**
 * Success.
 */
#define GAMUT_OK 0

/**
 * The operation rejected its input (the C mapping of `gamut_core::ErrorKind::InvalidInput`).
 */
#define GAMUT_STATUS_INVALID_INPUT 1

/**
 * The operation is not supported (the C mapping of `gamut_core::ErrorKind::Unsupported`).
 */
#define GAMUT_STATUS_UNSUPPORTED 2

/**
 * An I/O error (the C mapping of `gamut_core::ErrorKind::Io`).
 */
#define GAMUT_STATUS_IO 3

/**
 * A required pointer argument was `NULL`. Boundary-only: never maps a Rust error.
 */
#define GAMUT_STATUS_NULL_ARGUMENT 4

/**
 * The call panicked inside the library; the panic was contained at the boundary and nothing
 * was unwound into the caller. Boundary-only.
 */
#define GAMUT_STATUS_PANIC 5

/**
 * A caller-supplied buffer is too small. Boundary-only; reserved for the consumer entry
 * points of issue #242.
 */
#define GAMUT_STATUS_BUFFER_TOO_SMALL 6

/**
 * The pushed vtable's `abi_version` is not this library's [`GAMUT_CODEC_ABI_VERSION`] — the
 * backend was built against another generation of the seam and must be rebuilt. The caller
 * retains ownership of its `ctx`; no `destroy` has run. Boundary-only, and deliberately
 * distinct from [`GAMUT_STATUS_UNSUPPORTED`]: version skew asks for a rebuild, a declining
 * backend asks for a fallback.
 */
#define GAMUT_STATUS_ABI_MISMATCH 7

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Creates an AVIF encoder with default (lossless) settings and an empty backend registry.
 *
 * Returns `NULL` only if construction panics. Free with `gamut_avif_encoder_free`.
 */
struct GamutAvifEncoder *gamut_avif_encoder_new(void);

/**
 * Frees an encoder created by `gamut_avif_encoder_new`, running each adopted backend's
 * `destroy` exactly once. No-op on `NULL`.
 *
 * # Safety
 *
 * `encoder` is `NULL` or a pointer returned by `gamut_avif_encoder_new` that has not already
 * been freed.
 */
void gamut_avif_encoder_free(struct GamutAvifEncoder *encoder);

/**
 * Pushes an AV1 still-picture encode backend; backends are tried in push order, before the
 * built-in `gamut-av1` encoder.
 *
 * Returns `GAMUT_OK` when the handle adopts `ctx` (its `destroy` then runs exactly once, at
 * free), `GAMUT_STATUS_NULL_ARGUMENT` on a `NULL` encoder or vtable, or
 * `GAMUT_STATUS_ABI_MISMATCH` when `vtable->abi_version != GAMUT_CODEC_ABI_VERSION`; on any
 * non-OK status the caller keeps ownership of `ctx` and no callback has run.
 *
 * # Safety
 *
 * `encoder` as in `gamut_avif_encoder_free`; a non-`NULL` `vtable` points to a table that
 * stays valid for the encoder's lifetime. Calling this asserts the `(vtable, ctx)` backend
 * may be used from any thread (the registry requires `Send`).
 */
gamut_status_t gamut_avif_encoder_push_backend(struct GamutAvifEncoder *encoder,
                                               const struct GamutEncoderVTable *vtable,
                                               void *ctx);

/**
 * Creates a HEIC decoder with an empty backend registry.
 *
 * gamut ships no built-in HEVC decoder: until a backend is pushed, the handle can parse
 * containers (issue #242) but decodes nothing. Returns `NULL` only if construction panics.
 * Free with `gamut_heic_decoder_free`.
 */
struct GamutHeicDecoder *gamut_heic_decoder_new(void);

/**
 * Frees a decoder created by `gamut_heic_decoder_new`, running each adopted backend's
 * `destroy` exactly once. No-op on `NULL`.
 *
 * # Safety
 *
 * `decoder` is `NULL` or a pointer returned by `gamut_heic_decoder_new` that has not already
 * been freed.
 */
void gamut_heic_decoder_free(struct GamutHeicDecoder *decoder);

/**
 * Pushes an HEVC intra-decode backend; backends are consulted in push order (there is no
 * built-in tail).
 *
 * Returns `GAMUT_OK` when the handle adopts `ctx` (its `destroy` then runs exactly once, at
 * free), `GAMUT_STATUS_NULL_ARGUMENT` on a `NULL` decoder or vtable, or
 * `GAMUT_STATUS_ABI_MISMATCH` when `vtable->abi_version != GAMUT_CODEC_ABI_VERSION`; on any
 * non-OK status the caller keeps ownership of `ctx` and no callback has run.
 *
 * # Safety
 *
 * `decoder` as in `gamut_heic_decoder_free`; a non-`NULL` `vtable` points to a table that
 * stays valid for the decoder's lifetime. Calling this asserts the `(vtable, ctx)` backend
 * may be used from any thread.
 */
gamut_status_t gamut_heic_decoder_push_backend(struct GamutHeicDecoder *decoder,
                                               const struct GamutDecoderVTable *vtable,
                                               void *ctx);

/**
 * Creates a JPEG decoder with default limits and an empty backend registry.
 *
 * Returns `NULL` only if construction panics. Free with `gamut_jpeg_decoder_free`.
 */
struct GamutJpegDecoder *gamut_jpeg_decoder_new(void);

/**
 * Frees a decoder created by `gamut_jpeg_decoder_new`, running each adopted backend's
 * `destroy` exactly once. No-op on `NULL`.
 *
 * # Safety
 *
 * `decoder` is `NULL` or a pointer returned by `gamut_jpeg_decoder_new` that has not already
 * been freed.
 */
void gamut_jpeg_decoder_free(struct GamutJpegDecoder *decoder);

/**
 * Pushes a JPEG stream-decode backend; backends are tried in push order, before the built-in
 * decoder.
 *
 * Returns `GAMUT_OK` when the handle adopts `ctx` (its `destroy` then runs exactly once, at
 * free), `GAMUT_STATUS_NULL_ARGUMENT` on a `NULL` decoder or vtable, or
 * `GAMUT_STATUS_ABI_MISMATCH` when `vtable->abi_version != GAMUT_CODEC_ABI_VERSION`; on any
 * non-OK status the caller keeps ownership of `ctx` and no callback has run.
 *
 * # Safety
 *
 * `decoder` as in `gamut_jpeg_decoder_free`; a non-`NULL` `vtable` points to a table that
 * stays valid for the decoder's lifetime. Calling this asserts the `(vtable, ctx)` backend
 * may be used from any thread (the registry requires `Send`).
 */
gamut_status_t gamut_jpeg_decoder_push_backend(struct GamutJpegDecoder *decoder,
                                               const struct GamutDecoderVTable *vtable,
                                               void *ctx);

/**
 * Creates a JPEG encoder with default settings and an empty backend registry.
 *
 * Returns `NULL` only if construction panics. Free with `gamut_jpeg_encoder_free`.
 */
struct GamutJpegEncoder *gamut_jpeg_encoder_new(void);

/**
 * Frees an encoder created by `gamut_jpeg_encoder_new`, running each adopted backend's
 * `destroy` exactly once. No-op on `NULL`.
 *
 * # Safety
 *
 * `encoder` is `NULL` or a pointer returned by `gamut_jpeg_encoder_new` that has not already
 * been freed.
 */
void gamut_jpeg_encoder_free(struct GamutJpegEncoder *encoder);

/**
 * Pushes a JPEG stream-encode backend; backends are tried in push order, before the built-in
 * encoder.
 *
 * Status and ownership contract as for `gamut_jpeg_decoder_push_backend`.
 *
 * # Safety
 *
 * `encoder` as in `gamut_jpeg_encoder_free`; a non-`NULL` `vtable` points to a table that
 * stays valid for the encoder's lifetime. Calling this asserts the `(vtable, ctx)` backend
 * may be used from any thread (the registry requires `Send`).
 */
gamut_status_t gamut_jpeg_encoder_push_backend(struct GamutJpegEncoder *encoder,
                                               const struct GamutEncoderVTable *vtable,
                                               void *ctx);

/**
 * Creates a JPEG XL decoder with default settings and an empty backend registry.
 *
 * Returns `NULL` only if construction panics. Free with `gamut_jxl_decoder_free`.
 */
struct GamutJxlDecoder *gamut_jxl_decoder_new(void);

/**
 * Frees a decoder created by `gamut_jxl_decoder_new`, running each adopted backend's
 * `destroy` exactly once. No-op on `NULL`.
 *
 * # Safety
 *
 * `decoder` is `NULL` or a pointer returned by `gamut_jxl_decoder_new` that has not already
 * been freed.
 */
void gamut_jxl_decoder_free(struct GamutJxlDecoder *decoder);

/**
 * Pushes a JXL codestream-decode backend; backends are tried in push order, before the
 * built-in decoder.
 *
 * Returns `GAMUT_OK` when the handle adopts `ctx` (its `destroy` then runs exactly once, at
 * free), `GAMUT_STATUS_NULL_ARGUMENT` on a `NULL` decoder or vtable, or
 * `GAMUT_STATUS_ABI_MISMATCH` when `vtable->abi_version != GAMUT_CODEC_ABI_VERSION`; on any
 * non-OK status the caller keeps ownership of `ctx` and no callback has run.
 *
 * # Safety
 *
 * `decoder` as in `gamut_jxl_decoder_free`; a non-`NULL` `vtable` points to a table that
 * stays valid for the decoder's lifetime. Calling this asserts the `(vtable, ctx)` backend
 * may be used from any thread (the registry requires `Send`).
 */
gamut_status_t gamut_jxl_decoder_push_backend(struct GamutJxlDecoder *decoder,
                                              const struct GamutDecoderVTable *vtable,
                                              void *ctx);

/**
 * Creates a JPEG XL encoder with default settings and an empty backend registry.
 *
 * Returns `NULL` only if construction panics. Free with `gamut_jxl_encoder_free`.
 */
struct GamutJxlEncoder *gamut_jxl_encoder_new(void);

/**
 * Frees an encoder created by `gamut_jxl_encoder_new`, running each adopted backend's
 * `destroy` exactly once. No-op on `NULL`.
 *
 * # Safety
 *
 * `encoder` is `NULL` or a pointer returned by `gamut_jxl_encoder_new` that has not already
 * been freed.
 */
void gamut_jxl_encoder_free(struct GamutJxlEncoder *encoder);

/**
 * Pushes a JXL codestream-encode backend; backends are tried in push order, before the
 * built-in encoder.
 *
 * Status and ownership contract as for `gamut_jxl_decoder_push_backend`.
 *
 * # Safety
 *
 * `encoder` as in `gamut_jxl_encoder_free`; a non-`NULL` `vtable` points to a table that
 * stays valid for the encoder's lifetime. Calling this asserts the `(vtable, ctx)` backend
 * may be used from any thread (the registry requires `Send`).
 */
gamut_status_t gamut_jxl_encoder_push_backend(struct GamutJxlEncoder *encoder,
                                              const struct GamutEncoderVTable *vtable,
                                              void *ctx);

/**
 * Creates a PNG decoder with default limits and an empty backend registry.
 *
 * Returns `NULL` only if construction panics. Free with `gamut_png_decoder_free`.
 */
struct GamutPngDecoder *gamut_png_decoder_new(void);

/**
 * Frees a decoder created by `gamut_png_decoder_new`, running each adopted backend's
 * `destroy` exactly once. No-op on `NULL`.
 *
 * # Safety
 *
 * `decoder` is `NULL` or a pointer returned by `gamut_png_decoder_new` that has not already
 * been freed.
 */
void gamut_png_decoder_free(struct GamutPngDecoder *decoder);

/**
 * Pushes an IDAT-inflate backend; backends are tried in push order, before the built-in
 * inflate.
 *
 * Returns `GAMUT_OK` when the handle adopts `ctx` (its `destroy` then runs exactly once, at
 * free), `GAMUT_STATUS_NULL_ARGUMENT` on a `NULL` decoder or vtable, or
 * `GAMUT_STATUS_ABI_MISMATCH` when `vtable->abi_version != GAMUT_CODEC_ABI_VERSION`; on any
 * non-OK status the caller keeps ownership of `ctx` and no callback has run.
 *
 * # Safety
 *
 * `decoder` as in `gamut_png_decoder_free`; a non-`NULL` `vtable` points to a table that
 * stays valid for the decoder's lifetime. Calling this asserts the `(vtable, ctx)` backend
 * may be used from any thread (the registry requires `Send`).
 */
gamut_status_t gamut_png_decoder_push_backend(struct GamutPngDecoder *decoder,
                                              const struct GamutDecoderVTable *vtable,
                                              void *ctx);

/**
 * Creates a PNG encoder with default settings and an empty backend registry.
 *
 * Returns `NULL` only if construction panics. Free with `gamut_png_encoder_free`.
 */
struct GamutPngEncoder *gamut_png_encoder_new(void);

/**
 * Frees an encoder created by `gamut_png_encoder_new`, running each adopted backend's
 * `destroy` exactly once. No-op on `NULL`.
 *
 * # Safety
 *
 * `encoder` is `NULL` or a pointer returned by `gamut_png_encoder_new` that has not already
 * been freed.
 */
void gamut_png_encoder_free(struct GamutPngEncoder *encoder);

/**
 * Pushes an IDAT-deflate backend; backends are tried in push order, before the built-in
 * deflate.
 *
 * Status and ownership contract as for `gamut_png_decoder_push_backend`.
 *
 * # Safety
 *
 * `encoder` as in `gamut_png_encoder_free`; a non-`NULL` `vtable` points to a table that
 * stays valid for the encoder's lifetime. Calling this asserts the `(vtable, ctx)` backend
 * may be used from any thread (the registry requires `Send`).
 */
gamut_status_t gamut_png_encoder_push_backend(struct GamutPngEncoder *encoder,
                                              const struct GamutEncoderVTable *vtable,
                                              void *ctx);

/**
 * Creates a WebP decoder with default settings and an empty backend registry.
 *
 * Returns `NULL` only if construction panics. Free with `gamut_webp_decoder_free`.
 */
struct GamutWebpDecoder *gamut_webp_decoder_new(void);

/**
 * Frees a decoder created by `gamut_webp_decoder_new`, running each adopted backend's
 * `destroy` exactly once. No-op on `NULL`.
 *
 * # Safety
 *
 * `decoder` is `NULL` or a pointer returned by `gamut_webp_decoder_new` that has not already
 * been freed.
 */
void gamut_webp_decoder_free(struct GamutWebpDecoder *decoder);

/**
 * Pushes a WebP codestream-decode backend; backends are tried in push order, before the
 * built-in decoder.
 *
 * Returns `GAMUT_OK` when the handle adopts `ctx` (its `destroy` then runs exactly once, at
 * free), `GAMUT_STATUS_NULL_ARGUMENT` on a `NULL` decoder or vtable, or
 * `GAMUT_STATUS_ABI_MISMATCH` when `vtable->abi_version != GAMUT_CODEC_ABI_VERSION`; on any
 * non-OK status the caller keeps ownership of `ctx` and no callback has run.
 *
 * # Safety
 *
 * `decoder` as in `gamut_webp_decoder_free`; a non-`NULL` `vtable` points to a table that
 * stays valid for the decoder's lifetime. Calling this asserts the `(vtable, ctx)` backend
 * may be used from any thread (the registry requires `Send`).
 */
gamut_status_t gamut_webp_decoder_push_backend(struct GamutWebpDecoder *decoder,
                                               const struct GamutDecoderVTable *vtable,
                                               void *ctx);

/**
 * Creates a WebP encoder with default settings and an empty backend registry.
 *
 * Returns `NULL` only if construction panics. Free with `gamut_webp_encoder_free`.
 */
struct GamutWebpEncoder *gamut_webp_encoder_new(void);

/**
 * Frees an encoder created by `gamut_webp_encoder_new`, running each adopted backend's
 * `destroy` exactly once. No-op on `NULL`.
 *
 * # Safety
 *
 * `encoder` is `NULL` or a pointer returned by `gamut_webp_encoder_new` that has not already
 * been freed.
 */
void gamut_webp_encoder_free(struct GamutWebpEncoder *encoder);

/**
 * Pushes a WebP codestream-encode backend; backends are tried in push order, before the
 * built-in encoder.
 *
 * Status and ownership contract as for `gamut_webp_decoder_push_backend`.
 *
 * # Safety
 *
 * `encoder` as in `gamut_webp_encoder_free`; a non-`NULL` `vtable` points to a table that
 * stays valid for the encoder's lifetime. Calling this asserts the `(vtable, ctx)` backend
 * may be used from any thread (the registry requires `Send`).
 */
gamut_status_t gamut_webp_encoder_push_backend(struct GamutWebpEncoder *encoder,
                                               const struct GamutEncoderVTable *vtable,
                                               void *ctx);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* GAMUT_H */
